# Predicciones sobre Modelo Final
En este cuaderno se carga el modelo final conseguido anteriormente.

In [1]:
import pickle
with open ('modelo_final.pkl', 'rb') as file:
    modelo_final = pickle.load(file)

A continuación, cargamos el conjunto de datos de competición:

In [2]:
import pandas as pd
wind_comp=pd.read_csv('wind_comp.csv.gz', compression = "gzip")

In [12]:
wind_comp.shape

(1189, 23)

El conjunto de datos siguiente debe ser preprocesado para adaptarse correctamente al modelo con el que se obtendrán las predicciones.

In [3]:
wind_comp.head()

,datetime,p54.162.1,p54.162.2,p54.162.3,p54.162.4,p54.162.5,p54.162.6,p54.162.7,p54.162.8,p54.162.9,...,v100.16,v100.17,v100.18,v100.19,v100.20,v100.21,v100.22,v100.23,v100.24,v100.25
0,2010-01-01 00:00:00,2.403131e+06,2.395445e+06,2.387755e+06,2.380065e+06,2.372380e+06,2.399548e+06,2.391582e+06,2.383621e+06,2.375660e+06,...,7.212586,7.057422,6.901760,6.746597,6.591434,7.184147,7.030980,6.877313,6.723647,6.570479
1,2010-01-01 06:00:00,2.410306e+06,2.402394e+06,2.394483e+06,2.386571e+06,2.378660e+06,2.406786e+06,2.398599e+06,2.390412e+06,2.382225e+06,...,0.207289,0.583972,0.960654,1.337836,1.714518,0.345988,0.723170,1.100850,1.478031,1.855712
2,2010-01-01 12:00:00,2.434908e+06,2.426793e+06,2.418683e+06,2.410573e+06,2.402462e+06,2.431465e+06,2.423075e+06,2.414689e+06,2.406298e+06,...,1.670114,1.691568,1.712522,1.733976,1.754930,1.664127,1.682587,1.700548,1.718509,1.736470
3,2010-01-01 18:00:00,2.447112e+06,2.439069e+06,2.431027e+06,2.422984e+06,2.414942e+06,2.443696e+06,2.435378e+06,2.427060e+06,2.418742e+06,...,1.217597,1.278464,1.339332,1.399701,1.460569,1.215102,1.272477,1.329853,1.387228,1.444105
4,2010-01-02 00:00:00,2.459695e+06,2.451752e+06,2.443809e+06,2.435866e+06,2.427923e+06,2.456252e+06,2.448034e+06,2.439815e+06,2.431596e+06,...,3.755089,3.686738,3.617887,3.549536,3.481184,3.781532,3.710686,3.640338,3.569492,3.498646

Como se puede observar, este dataset no tiene el índice indicado, que debería ser la columna 'datetime', y contiene los datos de todas las regiones del mapa, mientras que en este caso sólo se necesitan los datos relativos a la zona 13. 

En primer lugar, se modifica el índice de los datos y se comprueba que el cambio se ha realizado correctamente. Adicionalmente, se modifica el tipo de datos de la columna 'datetime' al tipo *datetime*, para ajustarnos completamente al modelo.

In [4]:
wind_comp['datetime'] = pd.to_datetime(wind_comp['datetime'])
wind_comp = wind_comp.set_index('datetime')
wind_comp.head()

,p54.162.1,p54.162.2,p54.162.3,p54.162.4,p54.162.5,p54.162.6,p54.162.7,p54.162.8,p54.162.9,p54.162.10,...,v100.16,v100.17,v100.18,v100.19,v100.20,v100.21,v100.22,v100.23,v100.24,v100.25
datetime,,,,,,,,,,,,,,,,,,,,,
2010-01-01 00:00:00,2.403131e+06,2.395445e+06,2.387755e+06,2.380065e+06,2.372380e+06,2.399548e+06,2.391582e+06,2.383621e+06,2.375660e+06,2.367699e+06,...,7.212586,7.057422,6.901760,6.746597,6.591434,7.184147,7.030980,6.877313,6.723647,6.570479
2010-01-01 06:00:00,2.410306e+06,2.402394e+06,2.394483e+06,2.386571e+06,2.378660e+06,2.406786e+06,2.398599e+06,2.390412e+06,2.382225e+06,2.374038e+06,...,0.207289,0.583972,0.960654,1.337836,1.714518,0.345988,0.723170,1.100850,1.478031,1.855712
2010-01-01 12:00:00,2.434908e+06,2.426793e+06,2.418683e+06,2.410573e+06,2.402462e+06,2.431465e+06,2.423075e+06,2.414689e+06,2.406298e+06,2.397912e+06,...,1.670114,1.691568,1.712522,1.733976,1.754930,1.664127,1.682587,1.700548,1.718509,1.736470
2010-01-01 18:00:00,2.447112e+06,2.439069e+06,2.431027e+06,2.422984e+06,2.414942e+06,2.443696e+06,2.435378e+06,2.427060e+06,2.418742e+06,2.410423e+06,...,1.217597,1.278464,1.339332,1.399701,1.460569,1.215102,1.272477,1.329853,1.387228,1.444105
2010-01-02 00:00:00,2.459695e+06,2.451752e+06,2.443809e+06,2.435866e+06,2.427923e+06,2.456252e+06,2.448034e+06,2.439815e+06,2.431596e+06,2.423377e+06,...,3.755089,3.686738,3.617887,3.549536,3.481184,3.781532,3.710686,3.640338,3.569492,3.498646

En segundo lugar, se eliminan todas las columnas o variables de los datos irrelevantes para el problema planteado. Es decir, se mantienen únicamente las variables relativas al sector 13 del mapa.

In [5]:
for c in wind_comp.columns:
    if not c.endswith('.13') and c != 'datetime':
        wind_comp = wind_comp.drop(c, axis = 1)
        
wind_comp.head()

,p54.162.13,p55.162.13,cape.13,p59.162.13,lai_lv.13,lai_hv.13,u10n.13,v10n.13,sp.13,stl1.13,...,t2m.13,stl2.13,stl3.13,iews.13,inss.13,stl4.13,fsr.13,flsr.13,u100.13,v100.13
datetime,,,,,,,,,,,,,,,,,,,,,
2010-01-01 00:00:00,2.380345e+06,10.537942,10.382510,2.220341e+06,2.346936,2.433955,1.258152,4.389059,96056.601316,278.713081,...,277.372035,280.494544,282.003767,0.223763,0.469945,285.865293,0.426499,-5.692383,3.028044,6.801977
2010-01-01 06:00:00,2.387186e+06,11.038628,1.136771,3.593417e+06,2.346543,2.433821,0.258600,-0.063731,96132.834569,278.298853,...,276.877148,280.011630,281.986895,0.049144,0.037347,285.844043,0.426720,-5.673355,1.905932,0.819461
2010-01-01 12:00:00,2.411521e+06,9.635489,0.265247,4.477477e+06,2.346151,2.433676,4.505959,1.314488,96882.102158,280.531223,...,281.085733,279.880559,281.958683,0.363838,0.075026,285.823566,0.420984,-5.772643,6.254707,1.658140
2010-01-01 18:00:00,2.423920e+06,10.724937,4.281838,6.237006e+06,2.345759,2.433542,1.620416,0.278042,97243.861285,279.684007,...,278.417187,280.376232,281.945406,0.152444,0.057106,285.803281,0.418642,-5.807686,4.680087,1.276968
2010-01-02 00:00:00,2.436652e+06,13.533924,1.250448,5.666546e+06,2.345340,2.433397,0.958361,1.244256,97438.059470,277.778660,...,276.086144,279.878626,281.929364,0.098397,0.105619,285.783963,0.419667,-5.780384,2.686441,3.517605

Una vez, se ha realizado el preprocesado de los datos de competición, se procede a realizar predicciones sobre ellos mediante el modelo final.

In [6]:
pred = modelo_final.predict(wind_comp)

In [11]:
wind_comp.shape

(1189, 23)

Como último paso, se almacenan todas las predicciones en un Data Frame con una única columna encabezada como 'Predicciones'. A continuación, se convierte dicho Data Frame en un archivo CSV llamado *predicciones.csv*

In [7]:
wind_comp['energy_pred'] = pred

In [8]:
wind_comp['energy_pred'].to_csv('predicciones.csv')
#pred_df.to_csv('predicciones.csv', index=False)

In [10]:
wind_comp['energy_pred'].shape

(1189,)